apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Andreadote/Argocd.git
  password: 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sss #create your own token
  username: andreadote